### PR TITLE
simplify readiness probe

### PR DESCRIPTION
**Pull request by ltclm**
use a swisssearch request for the readiness check

### CODE REVIEW

**Review by ltshb — CHANGES_REQUESTED** [review]
I would not use the test client for productive ! Also using the rest endpoint cost a lot, the json response build cost in memory and cpu which in this case is not needed. You should use directly the sphinxapi and build a very simple request. Then only check that the query was successful.

**Comment by ltclm** [comment]
ok, ill change that next week. 
imho the advantage of this approach:
* it is a request every 10s, so the cost is not a real problem in my eyes
* we are testing under realistic conditions, same wsgi timeout and endpoint configuration as normal users

**Comment by ltclm** [comment]
@ltshb 
yes i will change the pr and implement a simple and slim sphinx api check.

fyi: the default ALB heath check interval is 30s
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html
it can't be less than 5s.

**Review by ltshb — APPROVED** [review]
👍🏼

**Pull request merged**
